config/routes.rb
Eatfit2::Application.routes.draw do


	root 'pages#front'

	as :user do
		get "/login" => "devise/sessions#new"
		delete "/logout" => "devise/sessions#destroy"
		get "/signup" => "devise/registrations#new"
		get "/account" => "devise/registrations#edit"
	end

	resources :meals, only: [:show, :new, :create, :destroy] do
		resources :comments, only: [:new, :create]
		member do
			post 'vote'
		end
	end

	namespace :admin do
		resources :overviews, only: [:index] do
			get 'users', on: :collection
			get 'meals', on: :collection
			get 'comments', on: :collection
		end
	end

	resources :relationships, only: [:create, :destroy]

	get 'activities', to: 'feeds#index'
	get 'search', to: 'search#search'
	post 'search', to: 'search#result'
	get 'friends', to: 'relationships#index'
	get 'followers', to: 'relationships#followers'

	get 'upload', to: 'dashboards#show'
	get 'contact', to: 'contact_messages#new'
	get 'timeline', to: 'timelines#show'
	get 'trending', to: 'showcases#index'

	post 'share_meal', to: 'meals#share'

	resources :contact_messages, only: [:create]

	get ':username', to: 'timelines#show', as: :user
	devise_for :users
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_filter :authenticate_user!

	def search
		users_not_to_display = current_user.leader_ids
		users_not_to_display << current_user.id
		@users = User.where("id NOT IN (?) AND avatar NOT IN (?)", users_not_to_display, true).limit(10)
	end

	def result
		@results = User.all_except(current_user).search_by_username(params[:search_term])
	end
end

app/views/search/result.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>Results<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>


<div class="contact">
  <div class="container">
    <div class="row" style="margin-top:20px;">
      <div class="col-md-12">
        <div class="well">
          <%= form_tag search_path, html: { class: "form-horizontal", role: "form" } do %>
            <fieldset>
              <div class="form-group">
                <div class="col-md-10 col-xs-12">
                  <%= text_field_tag :search_term, nil, class: "form-control", placeholder: "Search for Users here..." %>
                </div>
                <div class="col-md-2 col-xs-12">
                  <%= submit_tag "Search", class: "btn btn-primary" %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">

      <% @results.each do |user| %>
        <div class="col-md-6 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading"><%= link_to user.username.capitalize, user.username %></div>
              <div class="panel-body">
                <% if user.avatar.present? %>
                  <%= link_to image_tag(user.avatar, size: "60", class: "img-rounded"), user.username %>
                <% else %>
                  <%= link_to image_tag("avatar2.png", size: "60", class: "img-rounded"), user.username %>
                <% end %>
                <% if current_user.can_follow?(user) %>
                  <%= link_to "Follow", relationships_path(leader_id: user.id), method: :post, class: "btn btn-info follow-btn" %>
                <% else %>
                  <%= link_to "Friend", user.username, class: "btn btn-warning follow-btn" %>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/search/search.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>Find People<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>


<div class="contact">
  <div class="container">
    <div class="row" style="margin-top:20px;">
      <div class="col-md-12">
        <div class="well">
          <%= form_tag search_path, html: { class: "form-horizontal", role: "form" } do %>
            <fieldset>
              <div class="form-group">
                <div class="col-md-10 col-xs-12">
                  <%= text_field_tag :search_term, nil, class: "form-control", placeholder: "Search for Users here..." %>
                </div>
                <div class="col-md-2 col-xs-12">
                  <%= submit_tag "Search", class: "btn btn-primary" %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h4>People you might know:</h4>
      </div>

      <% @users.each do |user| %>
        <div class="col-md-6 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading"><%= link_to user.username.capitalize, user.username %></div>
              <div class="panel-body">
                <% if user.avatar.present? %>
                  <%= link_to image_tag(user.avatar, size: "60", class: "img-rounded"), user.username %>
                <% else %>
                  <%= link_to image_tag("avatar2.png", size: "60", class: "img-rounded"), user.username %>
                <% end %>
                <span><%= pluralize(user.leading_relationships.count, "Follower") %></span>
                <% if current_user.can_follow?(user) %>
                  <%= link_to "Follow", relationships_path(leader_id: user.id), method: :post, class: "btn btn-info follow-btn" %>
                <% elsif current_user == user %>
                  <%= link_to "You", current_user.username, class: "btn btn-warning follow-btn" %>
                <% else %>
                  <%= link_to "Friend", user.username, class: "btn btn-warning follow-btn" %>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>