config/routes.rb
Eatfit2::Application.routes.draw do


	root 'pages#front'

	as :user do
		get "/login" => "devise/sessions#new"
		delete "/logout" => "devise/sessions#destroy"
		get "/signup" => "devise/registrations#new"
		get "/account" => "devise/registrations#edit"
	end

	resources :meals, only: [:show, :new, :create, :destroy] do
		resources :comments, only: [:new, :create]
		member do
			post 'vote'
		end
	end

	namespace :admin do
		resources :overviews, only: [:index] do
			get 'users', on: :collection
			get 'meals', on: :collection
			get 'comments', on: :collection
		end
	end

	resources :relationships, only: [:create, :destroy]

	get 'activities', to: 'feeds#index'
	get 'search', to: 'search#search'
	post 'search', to: 'search#result'
	get 'friends', to: 'relationships#index'
	get 'followers', to: 'relationships#followers'

	get 'upload', to: 'dashboards#show'
	get 'contact', to: 'contact_messages#new'
	get 'timeline', to: 'timelines#show'
	get 'trending', to: 'showcases#index'

	post 'share_meal', to: 'meals#share'

	resources :contact_messages, only: [:create]

	get ':username', to: 'timelines#show', as: :user
	devise_for :users
end

app/controllers/admin/overviews_controller.rb
class Admin::OverviewsController < ApplicationController
	before_filter :authenticate_user!, :require_admin

	def index
	end

	def users
		@users = User.order("created_at DESC")
	end

	def meals
		@meals = Meal.order("created_at DESC").limit(10)
	end

	def comments
		@comments = Comment.order("created_at DESC").limit(50)
	end

	private

		def require_admin
			redirect_to root_path unless current_user.admin? == true
		end
end

app/views/admin/overviews/comments.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>Admin: Comments<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="blog">
  <div class="container">
    <div class="row center">
      <%= link_to "Users", users_admin_overviews_path, class: "btn btn-default" %>
      <%= link_to "Meals", meals_admin_overviews_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="about">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8 col-xs-12">
        <% @comments.each do |comment| %>
          <div class="query">
          <h3><%= comment.user.username %> <%= comment.created_at.strftime("%d. %h. %H:%M") %></h3>
          <hr>
            <p><%= comment.content %></p>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/overviews/index.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>Admin Overview<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="blog">
  <div class="container">
    <div class="row admin center">
      <%= link_to "Users", users_admin_overviews_path, class: "btn btn-default" %>
      <%= link_to "Meals", meals_admin_overviews_path, class: "btn btn-primary" %>
      <%= link_to "Comments", comments_admin_overviews_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/admin/overviews/meals.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>Admin: Meals<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="blog">
  <div class="container">
    <div class="row center">
      <%= link_to "Users", users_admin_overviews_path, class: "btn btn-default" %>
      <%= link_to "Comments", comments_admin_overviews_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

<div class="about">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8 col-xs-12">
        <% @meals.each do |meal| %>
          <div class="query">
          <h3><%= meal.user.username %>: <%= meal.created_at.strftime("%d. %h. %H:%M") %></h3>
          <hr>
            <%= image_tag meal.picture, size: "150" %>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/overviews/users.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>Admin: Users<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="blog">
  <div class="container">
    <div class="row center">
      <%= link_to "Meals", meals_admin_overviews_path, class: "btn btn-primary" %>
      <%= link_to "Comments", comments_admin_overviews_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

<div class="blog">
  <div class="container">
    <div class="row center">
      <table class="table table-striped">
        <tr>
          <th>Count: <%= @users.count %> Users</th>
          <th>Email</th>
          <th>Username</th>
          <th>SignInCount</th>
          <th>Created at</th>
          <th>Last Login</th>
        </tr>
        <% @users.each_with_index do |user, i| %>
          <tr>
            <td><%= i + 1 %></td>
            <td><%= user.email %></td>
            <td><%= user.username %></td>
            <td><%= user.sign_in_count %></td>
            <td><%= user.created_at.strftime("%d.%m.%y.") %></td>
            <td><%= user.last_sign_in_at.strftime("%d.%m.%y. (%H:%M)") %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>