config/routes.rb
Eatfit2::Application.routes.draw do


	root 'pages#front'

	as :user do
		get "/login" => "devise/sessions#new"
		delete "/logout" => "devise/sessions#destroy"
		get "/signup" => "devise/registrations#new"
		get "/account" => "devise/registrations#edit"
	end

	resources :meals, only: [:show, :new, :create, :destroy] do
		resources :comments, only: [:new, :create]
		member do
			post 'vote'
		end
	end

	namespace :admin do
		resources :overviews, only: [:index] do
			get 'users', on: :collection
			get 'meals', on: :collection
			get 'comments', on: :collection
		end
	end

	resources :relationships, only: [:create, :destroy]

	get 'activities', to: 'feeds#index'
	get 'search', to: 'search#search'
	post 'search', to: 'search#result'
	get 'friends', to: 'relationships#index'
	get 'followers', to: 'relationships#followers'

	get 'upload', to: 'dashboards#show'
	get 'contact', to: 'contact_messages#new'
	get 'timeline', to: 'timelines#show'
	get 'trending', to: 'showcases#index'

	post 'share_meal', to: 'meals#share'

	resources :contact_messages, only: [:create]

	get ':username', to: 'timelines#show', as: :user
	devise_for :users
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :leader, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@relationships = current_user.following_relationships.paginate(:page => params[:page], :per_page => 8)
	end

	def create
		@leader = User.find(params[:leader_id])
		Relationship.create(leader_id: params[:leader_id], follower: current_user) if current_user.can_follow?(@leader)
		redirect_to_back_or_default(user_path(@leader.username))
	end

	def destroy
		relationship = Relationship.find(params[:id])
		relationship.destroy if relationship.follower == current_user
		redirect_to friends_path
	end

	def followers
		@followers = User.where("id IN (?)", current_user.follower_ids).paginate(:page => params[:page], :per_page => 8)
	end
end

app/views/relationships/followers.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>My Followers<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>


<div class="contact">
  <div class="container">

    <div class="row center" style="margin-top: 20px;">
            <div class="col-md-offset-4 col-md-4 col-sm-4 col-xs-8">
        <div class="sidebar well">
          <div class="widget">
            <h3><%= current_user.username %></h3>
            <%= image_tag(current_user.avatar.url, size: "80") %>
            <ul class="friends-overview">
              <li><%= link_to "Followers: #{current_user.leading_relationships.count}", followers_path %></li>
              <li><%= link_to "Following: #{current_user.following_relationships.count}", friends_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="row center">
      <div class="col-md4 col-sm-12">
        <%= will_paginate @followers %>
      </div>
    </div>

    <div class="row" style="margin-top:20px;">
      <% if @followers == nil %>
        <div class="col-md-12">
          <h4>Your followers will be listed here:</h4>
        </div>
      <% end %>

      <% @followers.each do |follower| %>
        <div class="col-md-12 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading"><%= link_to follower.username.capitalize, user_path(follower.username) %></div>
              <div class="panel-body">
                <% if follower.avatar.present? %>
                  <%= link_to image_tag(follower.avatar, size: "60", class: "img-rounded"), user_path(follower.username) %>
                <% else %>
                  <%= link_to image_tag("avatar2.png", size: "60", class: "img-rounded"), user_path(follower.username) %>
                <% end %>
                <%= pluralize(follower.leading_relationships.count, "Follower") %>
              </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row center">
      <div class="col-md4 col-sm-12">
        <%= will_paginate @followers %>
      </div>
    </div>

  </div>
</div>

app/views/relationships/index.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>My Friends<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>


<div class="contact">
  <div class="container">

    <div class="row center">
      <div class="col-md4 col-sm-12">
        <%= will_paginate @relationships %>
      </div>
    </div>

    <div class="row" style="margin-top:20px;">
      <% if @relationships == nil %>
        <div class="col-md-12">
          <h4>Your friends will be listed here:</h4>
        </div>
      <% end %>

      <% @relationships.each do |relationship| %>
        <div class="col-md-6 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading"><%= link_to relationship.leader.username.capitalize, user_path(relationship.leader.username) %></div>
              <div class="panel-body">
                <% if relationship.leader.avatar.present? %>
                  <%= link_to image_tag(relationship.leader.avatar, size: "60", class: "img-rounded"), user_path(relationship.leader.username) %>
                <% else %>
                  <%= link_to image_tag("avatar2.png", size: "60", class: "img-rounded"), user_path(relationship.leader.username) %>
                <% end %>
                <%= pluralize(relationship.leader.leading_relationships.count, "Follower") %>
                <%= link_to "Unfollow", relationship, method: :delete, class: "btn btn-danger follow-btn" %>
              </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row center">
      <div class="col-md4 col-sm-12">
        <%= will_paginate @relationships %>
      </div>
    </div>
    
  </div>
</div>