config/routes.rb
Eatfit2::Application.routes.draw do


	root 'pages#front'

	as :user do
		get "/login" => "devise/sessions#new"
		delete "/logout" => "devise/sessions#destroy"
		get "/signup" => "devise/registrations#new"
		get "/account" => "devise/registrations#edit"
	end

	resources :meals, only: [:show, :new, :create, :destroy] do
		resources :comments, only: [:new, :create]
		member do
			post 'vote'
		end
	end

	namespace :admin do
		resources :overviews, only: [:index] do
			get 'users', on: :collection
			get 'meals', on: :collection
			get 'comments', on: :collection
		end
	end

	resources :relationships, only: [:create, :destroy]

	get 'activities', to: 'feeds#index'
	get 'search', to: 'search#search'
	post 'search', to: 'search#result'
	get 'friends', to: 'relationships#index'
	get 'followers', to: 'relationships#followers'

	get 'upload', to: 'dashboards#show'
	get 'contact', to: 'contact_messages#new'
	get 'timeline', to: 'timelines#show'
	get 'trending', to: 'showcases#index'

	post 'share_meal', to: 'meals#share'

	resources :contact_messages, only: [:create]

	get ':username', to: 'timelines#show', as: :user
	devise_for :users
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_filter :authenticate_user!

	def show
	end
end

app/views/dashboards/show.html.erb
<% content_for :hero do %>
<div class="hero inner-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="intro">
          <h2>Upload<span class="tblue">.</span></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="blog">
  <div class="container">
    <div class="row intro center">
      <div class="col-md-12">
        <div class="formdetails well">
          <%= form_for [Meal.new], html: { class: "form-horizontal", role: "form" } do |f| %>
            <fieldset>
              <div class="form-group">
                <%= f.label :picture, "New meal:", class: "col-lg-2 control-label" %>
                <div class="col-lg-9">
                  <%= f.file_field :picture, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-9">
                  <%= f.submit "Upload", class: "btn btn-primary btn-lg" %>
                  <%= link_to "Reset", upload_path, class: "btn btn-default" %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      <%# link_to "New Upload", new_meal_path, class: "btn btn-primary btn-lg new-upload" %>
      <h3>Your recent meals:</h3>
      </div>
    </div>
    <div class="row center">
      <% current_user.recent_meals.each do |meal| %>
        <div class="col-md-4 col-sm-12">
          <div class="posts">
            <div class="post-meta">
              <i class="icon-calendar"></i> <%= distance_of_time_in_words_to_now(meal.created_at) %> ago
              <!-- <i class="icon-comment"></i><%# link_to pluralize(meal.comments.count, "Comment"), meal %> -->
            </div>
            <%= link_to image_tag(meal.picture, class: "img-responsive img-thumbnail", size: "300"), meal %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>